### ISSUE TITLE
[1.20.1 - forge 47.3.0] and my game keeps crashing out of nowhere

### ISSUE THREAD

**Issue by Oreonii** [lgow/endofherobrine#37]
When i load into my game its fine for a few minutes but then freezes and crashes unexpectedly. i looked into the crash report and it says the suspected mod is "the end of herobrine" but i cant pinpoint what is actually wrong. i should also mention that i havent even played the modpack for maybe more than an hour and then it happened for the first time but now it happens after every few minutes i log in.

ive gotten exit code -1 everytime it crashes.  and this is what it's saying when I crash... "The game crashed whilst ticking entity
Error: java.util.ConcurrentModificationException: null"

i like this modpack and would like to continue playing it.

**Comment by Oreonii** [comment]
wow thanks for the help :/

**Comment by Confiac1563** [comment]
> wow thanks for the help :/

still bug bro
` java.lang.ArithmeticException: / by zero
	at net.mcreator.unknown.procedures.NullstalkerOnEntityTickUpdateProcedure.execute(NullstalkerOnEntityTickUpdateProcedure.java:41) ~[unknownnull-1.20.1-1.0.3.jar%23278!/:?] {re:classloading}
	at net.mcreator.unknown.entity.NullstalkerEntity.m_6075_(NullstalkerEntity.java:134) ~[unknownnull-1.20.1-1.0.3.jar%23278!/:?] {re:classloading}`
